name: test

on:
  pull_request:

jobs:
  golang:
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: auto
    steps:
      - uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Test
        run: ci/test.sh

      - name: Build
        run: ci/build.sh

      - uses: codecov/codecov-action@v3
        with:
          flags: go
